apiVersion: v1
kind: Namespace
metadata:
  name: helloworld-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-app
  namespace: helloworld-ns
spec:
  selector:
    matchLabels:
      app: helloworld-app
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworld-app
    spec:
      containers:
      - name: helloworld-app
        image: vital987/tomcat_helloworld:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-svc
  namespace: helloworld-ns
spec:
  selector:
    app: helloworld-app
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helloworld-ing
  namespace: helloworld-ns
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: helloworld-svc
            port:
              number: 80
